import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen flex bg-amber-50`}>
        <header className={"h-screen w-40 navbar flex justify-center"}>
          <div className={" w-full h-30 flex justify-center items-center"}>
            <img src="/logo.png" alt="Logo" className="w-20" />
          </div>

        </header>
        <div className={"w-screen"}>
            <nav className={"w-full h-30 text-5xl flex items-center navbar"}>WoodTrack</nav>
            {children}
        </div>
      </body>
    </html>
  );
}
